apiVersion: v1
kind: Service
metadata:
  labels:
  {{- include "charts.labels" . | nindent 4}}
  name: {{ .Values.service.name }}
spec:
  selector:
  {{- include "charts.selectorLabels" . | nindent 4}}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type}}
